In [2]:
import tensorflow as tf

In [4]:

r1=tf.constant(1,tf.int8)

In [5]:
r1

<tf.Tensor: shape=(), dtype=int8, numpy=1>

In [6]:
display(r1)

<tf.Tensor: shape=(), dtype=int8, numpy=1>

In [7]:
r1.shape

TensorShape([])

In [8]:
tf.shape(r1)


<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [9]:
r1.ndim 

0

In [10]:
r2=tf.constant(1,tf.int16,name="my_scalar")

In [11]:
r2

<tf.Tensor: shape=(), dtype=int16, numpy=1>

In [ ]:
r1_decimal=tf.constant(1.12345,tf.float32)

In [ ]:
r1_decimal

<tf.Tensor: shape=(), dtype=float32, numpy=1.12345>

In [ ]:
print(r1_decimal)

tf.Tensor(1.12345, shape=(), dtype=float32)


In [ ]:
print(r2)

tf.Tensor(1, shape=(), dtype=int16)


In [ ]:
r1_vector = tf.constant([1,3,5], tf.int16)

In [ ]:
r1_vector.shape

TensorShape([3])

In [ ]:
r1_vector.ndim

1

In [ ]:
r2_matrix=tf.constant([[1,2],[3,4]],tf.int16)

In [ ]:
r3_matrix=tf.constant([ [[1, 2],
                           [3, 4], 
                           [5, 6]] ], tf.int16)
print(r3_matrix)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)


In [ ]:
r10=tf.ones([10, 10])
print(r10)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


In [ ]:
x=tf.constant([2.0],dtype=tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)
